export enum ProductColors {
  WHITE = 'White',
  BLACK = 'Black',
  GRAY = 'Gray',
  SILVER = 'Silver',
  RED = 'Red',
  BLUE = 'Blue',
  BROWN = 'Brown',
  GREEN = 'Green',
  BEIGE = 'Beige',
  ORANGE = 'Orange',
  GOLD = 'Gold',
  YELLOW = 'Yellow',
  PURPLE = 'Purple',
}
